config/routes.rb
Trekky::Application.routes.draw do

  resources :travels do
    resources :activities do
      resources :comments
      resources :pictures
    end
  end

  resources :pictures
  
  resources :home do
    collection do
      match 'search' => 'home#search', :via => [:get, :post], :as  => :search
    end
  end

  devise_for :users
  resources :users, :only => [:show]


  #match '/users/edit' => "devise/sessions#new", as: :user_root
  match '/users/:id' => 'users#show', as: :user_root

  authenticated :user do
    root to: 'users#show'
  end

  root to: 'home#index'
end

app/models/travel.rb
# encoding: UTF-8
class Travel < ActiveRecord::Base

	belongs_to :user
	has_many :activities, :dependent => :destroy

	validates_presence_of :name, :start_country, :end_country
	validate :mydate_is_date?
	validate :start_travel_lower_end_travel
	
	has_attached_file :illustration, :styles => { :medium => "336x336>", :thumb => "154x154>" }, :default_url => "default_:style_travel.jpg"

	validates_attachment_content_type :illustration, :content_type => ["image/jpg","image/jpeg","image/png","image/gif"], :message => "Le format du fichier n'est pas bon"

	  private

	  def mydate_is_date?
	    if !self.start_travel.is_a?(Date)
	      self.errors.add(:start_travel, "Votre date de départ n'est pas du format JJ-MM-AAAA") 
	    end
	    if !self.end_travel.is_a?(Date)
	      self.errors.add(:end_travel, "Votre date de retour n'est pas du format JJ-MM-AAAA") 
	    end
	  end

	  def start_travel_lower_end_travel
	  	if !self.start_travel.nil? and !self.end_travel.nil? and self.start_travel > self.end_travel
	  		self.errors.add(:start_travel, "La date de départ doit être inférieur à la date de retour")
	  	end
	  end

end

app/controllers/travels_controller.rb
# encoding: UTF-8
class TravelsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource :only => [:new, :create, :edit, :update, :destroy]

  def index
    @travels = Travel.all
  end

  def show
    @travel = Travel.find(params[:id])
  end

  def new
    @user = User.find(current_user)
    @travel = Travel.new
  end

  def edit
    @travel = Travel.find(params[:id])
  end

  def create
    @user = User.find(current_user)
    @travel = @user.travels.new(params[:travel])

    if @travel.save
      redirect_to new_travel_activity_path(@travel.id), notice: 'Votre trek a bien été créé ! Ajoutez maintenant vos activités !'
    else
      render action: "new"
    end

  end

  def update
    @travel = Travel.find(params[:id])

    if @travel.update_attributes(params[:travel])
      redirect_to current_user, notice: 'Votre trek a bien été modifié !'
    else
      render action: "edit"
    end

  end

  def destroy
    @travel = Travel.find(params[:id])
    @travel.destroy
    redirect_to travels_url
  end
  
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/travels/_form.html.erb
<%= form_for(@travel) do |f| %>
  <% if @travel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@travel.errors.count, "erreur") %> ont été rencontrée(s) dans votre formulaire d'ajout de trek :</h2>

      <ul>
      <% @travel.errors.values.each do |msg| %>
        <li><%= msg.first %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="travel_name">Nom du trek</label>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <label for="travel_start_country">Pays de départ</label>
    <%= f.text_field :start_country %>
  </div>
  <div class="field">
    <label for="travel_end_country">Pays d'arrivé</label>
    <%= f.text_field :end_country %>
  </div>
  <div class="field">
    <label for="travel_start_travel">Date de début</label>
    <%= f.text_field :start_travel, :class => 'date_picker' %>
  </div>
  <div class="field">
    <label for="travel_end_travel">Date de fin</label>
    <%= f.text_field :end_travel, :class => 'date_picker' %>
  </div>
  <div>
    <%= f.label :illustration %>
    <%= f.file_field :illustration %>
  </div>
  <div class="actions">
    <%= f.submit "Enregistrer"%>
  </div>
<% end %>

app/views/travels/edit.html.erb
<div id="edit_trek">
	<div id="contenu_edit_trek">
		<h1>Editer mon trek</h1>

		<%= render 'form' %>

		<!--<%= link_to 'Show', @travel %> |
		<%= link_to 'Back', travels_path %>-->
		<div class="spacer"></div>
	</div>
</div>

app/views/travels/index.html.erb
<h1>Listing travels</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Start country</th>
    <th>End country</th>
    <th>Start travel</th>
    <th>End travel</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @travels.each do |travel| %>
  <tr>
    <td><%= travel.user_id %></td>
    <td><%= travel.name %></td>
    <td><%= travel.start_country %></td>
    <td><%= travel.end_country %></td>
    <td><%= travel.start_travel %></td>
    <td><%= travel.end_travel %></td>
    <td><%= link_to 'Show', travel %></td>
    <td><%= link_to 'Show activities', travel_activities_path(travel) %></td>
    <td><%= image_tag travel.illustration.url(:thumb) %></td>
    <td><%= link_to 'Edit', edit_travel_path(travel) if can? :manage, travel %></td>
    <td><%= link_to 'Destroy', travel, confirm: 'Are you sure?', method: :delete if can? :manage, travel %></td>
    <td><%= link_to 'Add Activity', new_travel_activity_path(travel) if can? :manage, travel %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Travel', new_travel_path %>

app/views/travels/new.html.erb
<div id="nouveau_trek">
	<div id="contenu_nouveau_trek">

	<h1>Nouveau trek</h1>

	<%= render 'form' %>

	<%= link_to 'Retour au profil', travels_path, :class => "retour" %>
	<div class="spacer"></div>
	</div>
</div>

app/views/travels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @travel.user_id %>
</p>

<p>
  <b>Name:</b>
  <%= @travel.name %>
</p>

<p>
  <b>Start country:</b>
  <%= @travel.start_country %>
</p>

<p>
  <b>End country:</b>
  <%= @travel.end_country %>
</p>

<p>
  <b>Start travel:</b>
  <%= @travel.start_travel %>
</p>

<p>
  <b>End travel:</b>
  <%= @travel.end_travel %>
</p>

<%= link_to 'Edit', edit_travel_path(@travel) if can? :manage, @travel %> 
<%= link_to 'Back', travels_path %>