config/routes.rb
Trekky::Application.routes.draw do

  resources :travels do
    resources :activities do
      resources :comments
      resources :pictures
    end
  end

  resources :pictures
  
  resources :home do
    collection do
      match 'search' => 'home#search', :via => [:get, :post], :as  => :search
    end
  end

  devise_for :users
  resources :users, :only => [:show]


  #match '/users/edit' => "devise/sessions#new", as: :user_root
  match '/users/:id' => 'users#show', as: :user_root

  authenticated :user do
    root to: 'users#show'
  end

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@last_activity = Activity.last
	end


	def search
   		@travels = @q.result(:distinct => true).paginate(:page => params[:page], :per_page => 5)
	end



	private

	  def resource_name
	    :user
	  end
	 
	  def resource
	    @resource ||= User.new
	  end
	 
	  def devise_mapping
	    @devise_mapping ||= Devise.mappings[:user]
	  end
		
end

app/views/home/index.html.erb
<div id="main_index">
	<div id="main_index_left">
			<h1>Le trek du jour</h1>

			<% if !@last_activity.nil? %>
				<div class="img_trek_du_jour">
					<%= link_to (image_tag @last_activity.travel.illustration.url(:medium)), travel_activities_path(@last_activity.travel) %>
				</div>
				<div class="description_trek_du_jour">
					<div class="title_trek_du_jour">
						<p class="title_trek_du_jour_date">
							Du <span><%= @last_activity.travel.start_travel %></span><br/>
							Au <span><%= @last_activity.travel.end_travel %></span>
						</p>
						<h2><%= @last_activity.travel.name %></h2>

						<h3><%= link_to "Par "+@last_activity.travel.user.pseudo, @last_activity.travel.user%></h3>
						<div class="description">
							<p><%= truncate(@last_activity.description, :length => 450) %></p>
							<p id="savoirplus"><%= link_to "Savoir plus", travel_activities_path(@last_activity.travel)%></p>
						</div>
					</div>
				</div>
			<% else %>
				Pas de trek du jour !
			<% end %>
	</div>

	<div id="main_index_right">
		<div id="main_index_right_top">
			<div class="h1_main_index_right_top">
				<h1>Connectes-toi</h1>
				<%= link_to "(ou inscris-toi maintenant !)", new_user_registration_url %>
			</div>
			<%= form_for("user", :url => user_session_path) do |f| %>
				<%= hidden_field_tag "provenance", "home" %>
				<%= f.text_field :pseudo, :value => "Pseudo" %><br/>
				<%= f.password_field :password, :value => "Mot de passe" %><br/>
				<!--<%= f.check_box :remember_me %>
				<%= f.label :remember_me %>-->
				<%= link_to "Mot de passe oublié ?", new_password_path('user') %><br/>
				<%= f.submit 'Connexion' %>
			<% end %>
		</div>

		<div id="reseaux">
                    <a class="facebook" name="fb_share" type="icon_link" share_url="<%= request.url %>"><%= image_tag("partage-facebook.png") %></a>
                    <script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>
                    <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= request.url %>" data-lang="fr">Tweeter</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                </div>

		<div id="main_index_right_bottom">

			<%= link_to "Ajouter un trek", new_travel_url, :id => "btn_ajouter" %>
			<div id="btn_facilement">Facilement et Rapidement</div>
		</div>
	</div>

	
</div>


app/views/home/search.html.erb
<div id="search">
    <div id="contenu_search">
        <h1>Resultat de votre recherche</h1>
        <% if @travels.count > 0 %>
            <table>

            <% @travels.each do |travel| %>
              <tr>
                <td class="col_photo">
                    <%= link_to (image_tag travel.illustration.url(:thumb)), travel_activities_path(travel) %>
                </td>
                <td class="col_desc">
                    <h2><%= link_to travel.name, travel_activities_path(travel) %></h2>
                    <%= link_to "par "+travel.user.pseudo, travel.user%><br><br>
                    <p>Un trek qui part de <%= travel.start_country %> et qui finit en <%= travel.end_country %></p>
                </td>
                <td class="col_dates">
                    <p>Du <span><%= travel.start_travel %></span><br/>
                    Au <span><%= travel.end_travel %></span></p>
                </td>
              </tr>
            <% end %>
            </table>
            <%= will_paginate @travels, :previous_label => t('helpers.labels.<'), :next_label => t('helpers.labels.>') %>
        <% else %>
            <p>Votre recherche n'a retourne aucun resultats</p>
        <% end %>

    </div>
</div>